spring:
  application:
    name: TMS
  profiles:
      active: dev
  datasource:
    url: jdbc:postgresql://dpg-d2k33k6mcj7s739r5n8g-a.oregon-postgres.render.com:5432/chat_app_0auk
    username: root
    password: mTodzaJU7q2B80sDJxxYUIuFg3Hxo5fD
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


server:
  port: 9092