spring:
  application:
    name: TMS
  profiles:
    active: dev
  datasource:
    url: jdbc:dpg-d2qpraer433s73en2elg-a.oregon-postgres.render.com/tms_rhri
    username: root
    password: ar4aam64STJyppbYs0RqDtyTgl2N9qPt
    

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


server:
  port: 9092
