spring:
  application:
    name: TMS
  profiles:
    active: dev
  datasource:
    url: jdbc:dpg-d2qo98adbo4c73cd20ag-a.oregon-postgres.render.com:5432/tms
    username: root
    password: xR6BgxujDAV6LN4ZyDxiHvQJSEMS7sjD
    

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


server:
  port: 9092