spring:
  application:
    name: TMS
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://root:LGs35L6AROw1WAmNGUtOTCS2r0Kiv3gV@dpg-d2rhicd6ubrc73en6oug-a.oregon-postgres.render.com:5432/tms_1ybu
    username: root
    password: LGs35L6AROw1WAmNGUtOTCS2r0Kiv3gV
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 9092
