spring:
  application:
    name: TMS

  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://root:wvPKQ9piPukw0ZHsjVXRHZKSBfYQuzHq@dpg-d2s7fv8gjchc73dunnc0-a.oregon-postgres.render.com:5432/tms_fsk0
    username: root
    password: wvPKQ9piPukw0ZHsjVXRHZKSBfYQuzHq
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


server:
  port: 9092
