spring:
  application:
    name: TMS
  profiles:
    active: dev
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/tms_db?createDatabaseIfNotExits=true}
    username: ${DB_USER:root}
    password: ${DB_USER:shubham}
    driver-class-name: org.postgresql.Driver
    

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


server:
  port: 9092
