spring:
  application:
    name: TMS
  profiles:
      active: dev
  datasource:
    url: jdbc:postgresql://root:8RFZFCxNcrhpXW9f49AdsL57cBL611Qa@dpg-d2rfj27diees73eaqb2g-a.oregon-postgres.render.com:5432/tms_rc8b
    username: root
    password: 8RFZFCxNcrhpXW9f49AdsL57cBL611Qa
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


server:
  port: 9092