spring:
  application:
    name: TMS
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://dpg-d2rg6cfdiees73ebima0-a.oregon-postgres.render.com:5432/tms_12pi
    username: root
    password: gMSwpTlp1jfxybpzwJSj4avXjLcvkNyo
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 9092